# config.yaml
fed_avg:
  min_fit_clients: 2
  min_available_clients: 2
  min_evaluate_clients: 0
  fraction_fit:   1.0
  fraction_evaluate: 0.0
  port: 8081

config:
  num_rounds: 1

orchestrator:
  max_clients_per_edge_server: 2
  run_edge_path: "/app/orchestrator/utils/run_edge_server.sh"
  kill_edge_path: "/app/orchestrator/utils/kill_edge_server.sh"

network:
  ip: 0.0.0.0
  port: 8080

