# config.yaml

federated_split:
  train: 0.10
  validation: 0.05

training:
  batch_size: 64          # mini-batch size
  seed: 42        # random seed for reproducibility
server:
  port: 8080              # TCP port for the edge servers
orchestrator:
  ip: "orchestrator"
  port: 8080            # TCP port for the orchestrator 
