# config.yaml
fed_avg:
  min_fit_clients: 3
  min_available_clients: 2
  min_evaluate_clients: 1
  fraction_fit:   1.0
  fraction_evaluate: 1.0

config:
  num_rounds: 3

logging:
  log_path: "./logs"

model:
  save_path: "./models/"
  model_name: "model.pth"

network:
  port: 8080

orchestrator:
  ip: "orchestrator"
  port: 8081