# config.yaml
fed_avg:
  min_fit_clients: 3
  min_available_clients: 2
  min_evaluate_clients: 1
  fraction_fit:   1.0
  fraction_evaluate: 1.0

config:
  num_rounds: 3

logging:
  log_path: "/app/edge_server/logs"

model:
  save_path: "/app/edge_server/models/"
  model_name: "model"
  load_path: "round_3_model.npz"

network:
  port: 8080

orchestrator:
  ip: "orchestrator"
  port: 8081